[tool.isort]
profile = "black"
line_length = 120

[tool.black]
line_length = 120

[tool.mypy]
strict = true
exclude = [
    ".venv"
]

[[tool.mypy.overrides]]
module = [
    "kaggle.*",
    "ml_metadata.*",
    "tensorflow_model_analysis.*",
    "tensorflow_transform.*",
    "tensorflow_recommenders.*",
    "tfx_bsl.public.*"
]
ignore_missing_imports = true
