[tool.isort]
profile = "black"
line_length = 120

[tool.black]
line_length = 120

[tool.mypy]
strict = true
exclude = [
    ".venv"
]

[[tool.mypy.overrides]]
module = [
    "kaggle.*",
    "tensorflow_transform.*"
]
ignore_missing_imports = true
